ajsute workflow

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -27,16 +27,13 @@ jobs:
         run: npm install -g @angular/cli@15.0.3
 
       - name: Run tests with coverage
-        run: npm test -- --coverage --coverageReporters=text-lcov | tee coverage.lcov
+        run: |
+          npx jest --coverage
+          if [ $? -ne 0 ]; then
+            echo "Failed to generate coverage report, stopping workflow..."
+            exit 1
+          fi
 
-      - name: Generate HTML coverage report
-        run: npx jest --coverage
-
-      - name: Upload coverage report
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage-report
-          path: coverage/html-report/
           
  #     - name: Running Unit Tests
  #       run: |
